/**
 * Internationalization for Tunecamp Web Wizard
 */

const translations = {
  it: {
    welcome: {
      title: "Benvenuto in Tunecamp",
      subtitle: "Crea il tuo sito musicale in pochi minuti",
      description: "Tunecamp ti aiuta a creare un sito web statico per la tua musica. Nessun database, nessun server complicato - solo file HTML che puoi hostare ovunque.",
      modeNewTitle: "Crea Nuovo Sito",
      modeNewDesc: "Inizia da zero",
      modeLoadTitle: "Carica Sito Esistente",
      modeLoadDesc: "Carica un file ZIP da una sessione precedente del wizard",
      zipUploadText: "Clicca o trascina per caricare il file ZIP",
      zipUploadHelp: "Seleziona un file ZIP generato precedentemente dal wizard Tunecamp",
      loadingZip: "Caricamento ZIP...",
      parsingZip: "Analisi file...",
      zipLoaded: "✓ Sito caricato con successo!",
      zipError: "Errore nel caricamento del ZIP. Assicurati che contenga i file catalog.yaml e/o artist.yaml (nella root o in una sottocartella).",
      modeSelectError: "Seleziona una modalità (Crea Nuovo o Carica Esistente)"
    },
    features: {
      audio: "Design audio-first",
      fast: "Velocissimo",
      responsive: "Mobile friendly"
    },
    catalog: {
      title: "Configura il Catalogo",
      subtitle: "Informazioni base del tuo sito musicale",
      catalogTitle: "Titolo del Catalogo",
      catalogDescription: "Descrizione",
      catalogUrl: "URL del Sito",
      headerImage: "Immagine Header (Opzionale)",
      headerImageHelp: "URL dell'immagine per lo sfondo dell'header",
      backgroundImage: "Immagine Sfondo Pagina (Opzionale)",
      backgroundImageHelp: "URL dell'immagine per lo sfondo di tutta la pagina"
    },
    artist: {
      title: "Informazioni Artista",
      subtitle: "Racconta chi sei",
      artistName: "Nome Artista",
      bio: "Biografia",
      socialLinks: "Link Social",
      addLink: "+ Aggiungi Link"
    },
    release: {
      title: "Release",
      subtitle: "Configura il tuo album o singolo",
      existingReleases: "Release esistenti caricate",
      addNewRelease: "Aggiungi nuova release",
      modifyRelease: "Modifica release esistente",
      selectRelease: "Seleziona una release da modificare",
      releaseTitle: "Titolo",
      releaseDate: "Data di Uscita",
      description: "Descrizione",
      genres: "Generi",
      genresHelp: "Separa i generi con virgole",
      coverUpload: "Immagine Copertina",
      coverUploadText: "Clicca o trascina per caricare la copertina",
      audioUpload: "Tracce Audio",
      audioUploadText: "Clicca o trascina per caricare i file audio"
    },
    download: {
      title: "Modalita Download",
      subtitle: "Come vuoi distribuire la tua musica?",
      modes: {
        free: { name: "Gratuito", description: "Download immediato senza restrizioni" },
        paycurtain: { name: "Paga Quanto Vuoi", description: "Suggerisci un prezzo, ma il download e' sempre possibile" },
        codes: { name: "Codici Sblocco", description: "Proteggi i download con codici univoci" },
        none: { name: "Solo Streaming", description: "Nessun download, solo ascolto" }
      },
      price: "Prezzo Suggerito",
      paypalLink: "Link PayPal (opzionale)",
      stripeLink: "Link Stripe (opzionale)"
    },
    summary: {
      title: "Riepilogo",
      subtitle: "Controlla la configurazione",
      catalogInfo: "Catalogo",
      artistInfo: "Artista",
      releaseInfo: "Release",
      downloadInfo: "Download",
      preview: "Anteprima"
    },
    success: {
      title: "Sito Pronto!",
      message: "Il tuo sito musicale completo e' stato generato.",
      nextSteps: "Prossimi Passi",
      step1: "Estrai il file ZIP",
      step2: "Carica la cartella su un hosting (Netlify, Vercel, GitHub Pages...)",
      step3: "Condividi la tua musica con il mondo!",
      hostingTips: "Opzioni Hosting Gratuite",
      tracks: "tracce",
      totalSize: "dimensione"
    },
    buttons: {
      back: "Indietro",
      next: "Avanti",
      generate: "Genera Sito",
      downloadZip: "Scarica Sito Completo"
    },
    building: {
      title: "Generazione in corso...",
      processing: "Elaborazione file audio",
      generating: "Creazione pagine HTML",
      packaging: "Preparazione ZIP"
    }
  },
  en: {
    welcome: {
      title: "Welcome to Tunecamp",
      subtitle: "Create your music website in minutes",
      description: "Tunecamp helps you create a static website for your music. No database, no complicated servers - just HTML files you can host anywhere.",
      modeNewTitle: "Create New Site",
      modeNewDesc: "Start from scratch",
      modeLoadTitle: "Load Existing Site",
      modeLoadDesc: "Upload a ZIP file from a previous wizard session",
      zipUploadText: "Click or drag to upload ZIP file",
      zipUploadHelp: "Select a ZIP file previously generated by Tunecamp wizard",
      loadingZip: "Loading ZIP...",
      parsingZip: "Parsing files...",
      zipLoaded: "✓ Site loaded successfully!",
      zipError: "Error loading ZIP. Make sure it's a ZIP file generated by Tunecamp wizard."
    },
    features: {
      audio: "Audio-first design",
      fast: "Lightning fast",
      themes: "5 beautiful themes",
      responsive: "Mobile friendly"
    },
    catalog: {
      title: "Configure Catalog",
      subtitle: "Basic information for your music site",
      catalogTitle: "Catalog Title",
      catalogDescription: "Description",
      catalogUrl: "Site URL"
    },
    artist: {
      title: "Artist Information",
      subtitle: "Tell us about yourself",
      artistName: "Artist Name",
      bio: "Biography",
      socialLinks: "Social Links",
      addLink: "+ Add Link"
    },
    release: {
      title: "Release",
      subtitle: "Configure your album or single",
      existingReleases: "Existing releases loaded",
      addNewRelease: "Add new release",
      modifyRelease: "Modify existing release",
      selectRelease: "Select a release to modify",
      releaseTitle: "Title",
      releaseDate: "Release Date",
      description: "Description",
      genres: "Genres",
      genresHelp: "Separate genres with commas",
      coverUpload: "Cover Image",
      coverUploadText: "Click or drag to upload cover image",
      audioUpload: "Audio Tracks",
      audioUploadText: "Click or drag to upload audio files"
    },
    download: {
      title: "Download Mode",
      subtitle: "How do you want to distribute your music?",
      modes: {
        free: { name: "Free", description: "Immediate download without restrictions" },
        paycurtain: { name: "Pay What You Want", description: "Suggest a price, but download is always available" },
        codes: { name: "Unlock Codes", description: "Protect downloads with unique codes" },
        none: { name: "Streaming Only", description: "No downloads, streaming only" }
      },
      price: "Suggested Price",
      paypalLink: "PayPal Link (optional)",
      stripeLink: "Stripe Link (optional)"
    },
    summary: {
      title: "Summary",
      subtitle: "Review your configuration",
      catalogInfo: "Catalog",
      artistInfo: "Artist",
      releaseInfo: "Release",
      downloadInfo: "Download",
      preview: "Preview"
    },
    success: {
      title: "Site Ready!",
      message: "Your complete music site has been generated.",
      nextSteps: "Next Steps",
      step1: "Extract the ZIP file",
      step2: "Upload to any web hosting (Netlify, Vercel, GitHub Pages...)",
      step3: "Share your music with the world!",
      hostingTips: "Free Hosting Options",
      tracks: "tracks",
      totalSize: "total size"
    },
    buttons: {
      back: "Back",
      next: "Next",
      generate: "Generate Site",
      downloadZip: "Download Complete Site"
    },
    building: {
      title: "Building...",
      processing: "Processing audio files",
      generating: "Generating HTML pages",
      packaging: "Packaging ZIP"
    }
  }
};

let currentLanguage = 'en';

function setLanguage(lang) {
  currentLanguage = lang;
  
  // Update language buttons
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.remove('active');
  });
  document.getElementById(`lang-${lang}`).classList.add('active');
  
  // Update all translatable elements
  updateTranslations();
}

function t(key) {
  const keys = key.split('.');
  let result = translations[currentLanguage];
  
  for (const k of keys) {
    if (result && typeof result === 'object' && k in result) {
      result = result[k];
    } else {
      return key;
    }
  }
  
  return typeof result === 'string' ? result : key;
}

function updateTranslations() {
  const lang = translations[currentLanguage];
  
  // Welcome
  document.getElementById('welcome-title').textContent = lang.welcome.title;
  document.getElementById('welcome-subtitle').textContent = lang.welcome.subtitle;
  document.getElementById('welcome-description').textContent = lang.welcome.description;
  
  // Mode selection
  const modeNewTitle = document.getElementById('mode-new-title');
  const modeNewDesc = document.getElementById('mode-new-desc');
  const modeLoadTitle = document.getElementById('mode-load-title');
  const modeLoadDesc = document.getElementById('mode-load-desc');
  const zipUploadText = document.getElementById('zip-upload-text');
  
  if (modeNewTitle) modeNewTitle.textContent = lang.welcome.modeNewTitle;
  if (modeNewDesc) modeNewDesc.textContent = lang.welcome.modeNewDesc;
  if (modeLoadTitle) modeLoadTitle.textContent = lang.welcome.modeLoadTitle;
  if (modeLoadDesc) modeLoadDesc.textContent = lang.welcome.modeLoadDesc;
  if (zipUploadText) zipUploadText.textContent = lang.welcome.zipUploadText;
  
  // Features
  const features = document.querySelectorAll('.feature-text');
  if (features.length >= 4) {
    features[0].textContent = lang.features.audio;
    features[1].textContent = lang.features.fast;
    features[2].textContent = lang.features.themes;
    features[3].textContent = lang.features.responsive;
  }
  
  // Catalog
  document.getElementById('catalog-title').textContent = lang.catalog.title;
  document.getElementById('catalog-subtitle').textContent = lang.catalog.subtitle;
  document.getElementById('label-catalog-title').textContent = lang.catalog.catalogTitle;
  document.getElementById('label-catalog-desc').textContent = lang.catalog.catalogDescription;
  document.getElementById('label-catalog-url').textContent = lang.catalog.catalogUrl;
  document.getElementById('label-select-theme').textContent = lang.catalog.selectTheme;
  
  // Artist
  document.getElementById('artist-title').textContent = lang.artist.title;
  document.getElementById('artist-subtitle').textContent = lang.artist.subtitle;
  document.getElementById('label-artist-name').textContent = lang.artist.artistName;
  document.getElementById('label-artist-bio').textContent = lang.artist.bio;
  document.getElementById('label-social-links').textContent = lang.artist.socialLinks;
  document.getElementById('btn-add-link').textContent = lang.artist.addLink;
  
  // Release
  document.getElementById('release-title').textContent = lang.release.title;
  document.getElementById('release-subtitle').textContent = lang.release.subtitle;
  document.getElementById('label-release-title').textContent = lang.release.releaseTitle;
  document.getElementById('label-release-date').textContent = lang.release.releaseDate;
  document.getElementById('label-release-desc').textContent = lang.release.description;
  document.getElementById('label-release-genres').textContent = lang.release.genres;
  document.getElementById('genres-help').textContent = lang.release.genresHelp;
  
  // File uploads
  const coverUploadLabel = document.getElementById('label-cover-upload');
  const audioUploadLabel = document.getElementById('label-audio-upload');
  const coverUploadText = document.getElementById('cover-upload-text');
  const audioUploadText = document.getElementById('audio-upload-text');
  
  if (coverUploadLabel) coverUploadLabel.textContent = lang.release.coverUpload;
  if (audioUploadLabel) audioUploadLabel.textContent = lang.release.audioUpload;
  if (coverUploadText) coverUploadText.textContent = lang.release.coverUploadText;
  if (audioUploadText) audioUploadText.textContent = lang.release.audioUploadText;
  
  // Background images
  const headerImageLabel = document.getElementById('label-header-image');
  const backgroundImageLabel = document.getElementById('label-background-image');
  const headerImageHelp = document.getElementById('header-image-help');
  const backgroundImageHelp = document.getElementById('background-image-help');
  
  if (headerImageLabel) headerImageLabel.textContent = lang.catalog.headerImage;
  if (backgroundImageLabel) backgroundImageLabel.textContent = lang.catalog.backgroundImage;
  if (headerImageHelp) headerImageHelp.textContent = lang.catalog.headerImageHelp;
  if (backgroundImageHelp) backgroundImageHelp.textContent = lang.catalog.backgroundImageHelp;
  
  // Download
  document.getElementById('download-title').textContent = lang.download.title;
  document.getElementById('download-subtitle').textContent = lang.download.subtitle;
  document.getElementById('mode-free-name').textContent = lang.download.modes.free.name;
  document.getElementById('mode-free-desc').textContent = lang.download.modes.free.description;
  document.getElementById('mode-paycurtain-name').textContent = lang.download.modes.paycurtain.name;
  document.getElementById('mode-paycurtain-desc').textContent = lang.download.modes.paycurtain.description;
  document.getElementById('mode-codes-name').textContent = lang.download.modes.codes.name;
  document.getElementById('mode-codes-desc').textContent = lang.download.modes.codes.description;
  document.getElementById('mode-none-name').textContent = lang.download.modes.none.name;
  document.getElementById('mode-none-desc').textContent = lang.download.modes.none.description;
  document.getElementById('label-price').textContent = lang.download.price;
  document.getElementById('label-paypal').textContent = lang.download.paypalLink;
  document.getElementById('label-stripe').textContent = lang.download.stripeLink;
  
  // Summary
  document.getElementById('summary-title').textContent = lang.summary.title;
  document.getElementById('summary-subtitle').textContent = lang.summary.subtitle;
  document.getElementById('summary-catalog-info').textContent = lang.summary.catalogInfo;
  document.getElementById('summary-artist-info').textContent = lang.summary.artistInfo;
  document.getElementById('summary-release-info').textContent = lang.summary.releaseInfo;
  document.getElementById('summary-download-info').textContent = lang.summary.downloadInfo;
  document.getElementById('preview-title').textContent = lang.summary.preview;
  
  // Success
  document.getElementById('success-title').textContent = lang.success.title;
  document.getElementById('success-message').textContent = lang.success.message;
  document.getElementById('next-steps-title').textContent = lang.success.nextSteps;
  document.getElementById('next-step-1').textContent = lang.success.step1;
  document.getElementById('next-step-2').textContent = lang.success.step2;
  document.getElementById('next-step-3').textContent = lang.success.step3;
  
  const hostingTipsTitle = document.getElementById('hosting-tips-title');
  if (hostingTipsTitle) hostingTipsTitle.textContent = lang.success.hostingTips;
  
  // Buttons
  document.getElementById('btn-back-text').textContent = lang.buttons.back;
  document.getElementById('btn-download-zip').innerHTML = '📦 ' + lang.buttons.downloadZip;
  
  // Update next button based on step
  updateNextButtonText();
}

function updateNextButtonText() {
  const lang = translations[currentLanguage];
  const btnNextText = document.getElementById('btn-next-text');
  
  if (currentStep === 6) {
    btnNextText.textContent = lang.buttons.generate;
  } else {
    btnNextText.textContent = lang.buttons.next;
  }
}
