import { spawn, type ChildProcess } from "child_process";
import path from "path";
import os from "os";
import fs from "fs-extra";

/**
 * HlsLiveService — server-side HLS pipeline for live audio sessions.
 *
 * The broadcaster's browser captures the microphone with MediaRecorder
 * (webm/opus) and POSTs chunks to the ingest endpoint. Each room gets one
 * persistent ffmpeg process that reads the webm stream from stdin and emits
 * a rolling HLS playlist (AAC segments) into a per-room temp directory.
 * Listeners pull the playlist over plain HTTP, so a single broadcaster
 * upload scales to as many listeners as the server's bandwidth allows —
 * unlike the previous WebRTC mesh, which uploaded one stream copy per
 * listener from the artist's browser.
 */

const SEGMENT_SECONDS = 4;
const PLAYLIST_SIZE = 6;          // rolling window: ~24s of audio on disk
const LISTENER_WINDOW_MS = 30_000; // a playlist poll within this window counts as a listener

interface HlsStream {
    roomId: string;
    dir: string;
    process: ChildProcess;
    /** clientKey -> last playlist request timestamp */
    listeners: Map<string, number>;
    /** Persistent recording file, when the session opted into recording. */
    recordingPath?: string;
}

export class HlsLiveService {
    private streams = new Map<string, HlsStream>();
    private baseDir: string;
    private recBaseDir: string;

    constructor(baseDir?: string) {
        this.baseDir = baseDir || path.join(os.tmpdir(), "tunecamp-live");
        // Recordings live outside the per-room HLS dir so they survive the
        // dir cleanup on stop() and can be ingested afterwards.
        this.recBaseDir = path.join(os.tmpdir(), "tunecamp-live-rec");
    }

    isActive(roomId: string): boolean {
        return this.streams.has(roomId);
    }

    /**
     * Spawns the ffmpeg HLS pipeline for a room. Idempotent per room:
     * a second start tears down the previous process first.
     *
     * With `record: true`, ffmpeg gets a second output that writes the full
     * session to a persistent MP4/AAC file (returned by stop()), so it can be
     * ingested as a track afterwards.
     */
    async start(roomId: string, opts: { record?: boolean } = {}): Promise<void> {
        await this.stop(roomId);

        const ffmpegBin = process.env.FFMPEG_PATH;
        if (!ffmpegBin) {
            throw new Error("FFmpeg not available: cannot start HLS live stream");
        }

        const dir = path.join(this.baseDir, roomId);
        await fs.ensureDir(dir);

        const args = [
            "-hide_banner", "-loglevel", "error",
            "-f", "webm", "-i", "pipe:0",
            // Live HLS output (rolling window)
            "-c:a", "aac", "-b:a", "128k", "-ac", "2",
            "-f", "hls",
            "-hls_time", String(SEGMENT_SECONDS),
            "-hls_list_size", String(PLAYLIST_SIZE),
            "-hls_flags", "delete_segments+omit_endlist",
            path.join(dir, "live.m3u8"),
        ];

        let recordingPath: string | undefined;
        if (opts.record) {
            await fs.ensureDir(this.recBaseDir);
            recordingPath = path.join(this.recBaseDir, `${roomId}.m4a`);
            // Second output: the complete session as a standalone file.
            args.push(
                "-c:a", "aac", "-b:a", "192k", "-ac", "2",
                "-f", "mp4",
                recordingPath,
            );
        }

        const proc = spawn(ffmpegBin, args, { stdio: ["pipe", "ignore", "pipe"] });

        proc.stderr?.on("data", (d: Buffer) => {
            console.error(`❌ [HLS ${roomId}] ffmpeg: ${d.toString().trim()}`);
        });
        proc.on("exit", (code) => {
            if (code !== 0 && code !== null) {
                console.warn(`⚠️ [HLS ${roomId}] ffmpeg exited with code ${code}`);
            }
        });
        // Broadcaster may disconnect abruptly; EPIPE on stdin is expected then
        proc.stdin?.on("error", () => {});

        this.streams.set(roomId, { roomId, dir, process: proc, listeners: new Map(), recordingPath });
        console.log(`📡 [HLS ${roomId}] Live pipeline started (${dir})${recordingPath ? " [recording]" : ""}`);
    }

    /**
     * Feeds a MediaRecorder chunk into the room's ffmpeg stdin.
     * Returns false if the room has no active pipeline.
     */
    ingest(roomId: string, chunk: Buffer): boolean {
        const stream = this.streams.get(roomId);
        if (!stream || !stream.process.stdin || stream.process.stdin.destroyed) {
            return false;
        }
        stream.process.stdin.write(chunk);
        return true;
    }

    /**
     * Resolves a playlist/segment request to a file path inside the room's
     * directory. Returns null for unknown rooms or path-traversal attempts.
     */
    resolveFile(roomId: string, fileName: string): string | null {
        const stream = this.streams.get(roomId);
        if (!stream) return null;

        // Only flat .m3u8/.ts names generated by ffmpeg are legitimate
        if (!/^[\w.-]+\.(m3u8|ts)$/.test(fileName)) return null;

        const resolved = path.resolve(stream.dir, fileName);
        if (!resolved.startsWith(path.resolve(stream.dir) + path.sep)) return null;
        return resolved;
    }

    /** Records a playlist poll so the listener shows up in the count. */
    trackListener(roomId: string, clientKey: string): void {
        const stream = this.streams.get(roomId);
        if (!stream) return;
        stream.listeners.set(clientKey, Date.now());
    }

    getListenerCount(roomId: string): number {
        const stream = this.streams.get(roomId);
        if (!stream) return 0;

        const cutoff = Date.now() - LISTENER_WINDOW_MS;
        for (const [key, lastSeen] of stream.listeners) {
            if (lastSeen < cutoff) stream.listeners.delete(key);
        }
        return stream.listeners.size;
    }

    /**
     * Tears down the ffmpeg process and removes the room's HLS segments.
     * Returns the recording file path if the session was being recorded (the
     * file lives outside the room dir, so it survives this cleanup), otherwise
     * null. The promise resolves only once ffmpeg has exited, so a returned
     * recording is fully flushed and safe to ingest.
     */
    async stop(roomId: string): Promise<string | null> {
        const stream = this.streams.get(roomId);
        if (!stream) return null;
        this.streams.delete(roomId);
        const recordingPath = stream.recordingPath ?? null;

        // Signal end-of-input and wait for ffmpeg to flush/finalize its outputs
        // (the recording's MP4 container is finalized on a clean exit). Force-kill
        // only if it overstays; recordings get a longer grace to finish writing.
        await new Promise<void>((resolve) => {
            let settled = false;
            const finish = () => { if (!settled) { settled = true; resolve(); } };
            const killTimer = setTimeout(() => {
                try { stream.process.kill("SIGKILL"); } catch {}
                finish();
            }, recordingPath ? 9000 : 3000);
            stream.process.once("exit", () => { clearTimeout(killTimer); finish(); });
            try { stream.process.stdin?.end(); } catch { finish(); }
        });

        try {
            await fs.remove(stream.dir);
        } catch (e) {
            console.error(`❌ [HLS ${roomId}] Cleanup failed:`, e);
        }
        console.log(`📡 [HLS ${roomId}] Live pipeline stopped`);
        return recordingPath;
    }

    /** Removes a finished recording file (e.g. after it has been ingested). */
    async discardRecording(recordingPath: string): Promise<void> {
        try { await fs.remove(recordingPath); } catch { /* best effort */ }
    }

    /** Stops every active pipeline (server shutdown). */
    async stopAll(): Promise<void> {
        await Promise.all([...this.streams.keys()].map(id => this.stop(id)));
    }
}
