import { spawn, type ChildProcess } from "child_process";
import path from "path";
import os from "os";
import fs from "fs-extra";

/**
 * HlsLiveService — server-side HLS pipeline for live audio sessions.
 *
 * The broadcaster's browser captures the microphone with MediaRecorder
 * (webm/opus) and POSTs chunks to the ingest endpoint. Each room gets one
 * persistent ffmpeg process that reads the webm stream from stdin and emits
 * a rolling HLS playlist (AAC segments) into a per-room temp directory.
 * Listeners pull the playlist over plain HTTP, so a single broadcaster
 * upload scales to as many listeners as the server's bandwidth allows —
 * unlike the previous WebRTC mesh, which uploaded one stream copy per
 * listener from the artist's browser.
 */

const SEGMENT_SECONDS = 4;
const PLAYLIST_SIZE = 6;          // rolling window: ~24s of audio on disk
const LISTENER_WINDOW_MS = 30_000; // a playlist poll within this window counts as a listener

interface HlsStream {
    roomId: string;
    dir: string;
    process: ChildProcess;
    /** clientKey -> last playlist request timestamp */
    listeners: Map<string, number>;
}

export class HlsLiveService {
    private streams = new Map<string, HlsStream>();
    private baseDir: string;

    constructor(baseDir?: string) {
        this.baseDir = baseDir || path.join(os.tmpdir(), "tunecamp-live");
    }

    isActive(roomId: string): boolean {
        return this.streams.has(roomId);
    }

    /**
     * Spawns the ffmpeg HLS pipeline for a room. Idempotent per room:
     * a second start tears down the previous process first.
     */
    async start(roomId: string): Promise<void> {
        await this.stop(roomId);

        const ffmpegBin = process.env.FFMPEG_PATH;
        if (!ffmpegBin) {
            throw new Error("FFmpeg not available: cannot start HLS live stream");
        }

        const dir = path.join(this.baseDir, roomId);
        await fs.ensureDir(dir);

        const proc = spawn(ffmpegBin, [
            "-hide_banner", "-loglevel", "error",
            "-f", "webm", "-i", "pipe:0",
            "-c:a", "aac", "-b:a", "128k", "-ac", "2",
            "-f", "hls",
            "-hls_time", String(SEGMENT_SECONDS),
            "-hls_list_size", String(PLAYLIST_SIZE),
            "-hls_flags", "delete_segments+omit_endlist",
            path.join(dir, "live.m3u8")
        ], { stdio: ["pipe", "ignore", "pipe"] });

        proc.stderr?.on("data", (d: Buffer) => {
            console.error(`❌ [HLS ${roomId}] ffmpeg: ${d.toString().trim()}`);
        });
        proc.on("exit", (code) => {
            if (code !== 0 && code !== null) {
                console.warn(`⚠️ [HLS ${roomId}] ffmpeg exited with code ${code}`);
            }
        });
        // Broadcaster may disconnect abruptly; EPIPE on stdin is expected then
        proc.stdin?.on("error", () => {});

        this.streams.set(roomId, { roomId, dir, process: proc, listeners: new Map() });
        console.log(`📡 [HLS ${roomId}] Live pipeline started (${dir})`);
    }

    /**
     * Feeds a MediaRecorder chunk into the room's ffmpeg stdin.
     * Returns false if the room has no active pipeline.
     */
    ingest(roomId: string, chunk: Buffer): boolean {
        const stream = this.streams.get(roomId);
        if (!stream || !stream.process.stdin || stream.process.stdin.destroyed) {
            return false;
        }
        stream.process.stdin.write(chunk);
        return true;
    }

    /**
     * Resolves a playlist/segment request to a file path inside the room's
     * directory. Returns null for unknown rooms or path-traversal attempts.
     */
    resolveFile(roomId: string, fileName: string): string | null {
        const stream = this.streams.get(roomId);
        if (!stream) return null;

        // Only flat .m3u8/.ts names generated by ffmpeg are legitimate
        if (!/^[\w.-]+\.(m3u8|ts)$/.test(fileName)) return null;

        const resolved = path.resolve(stream.dir, fileName);
        if (!resolved.startsWith(path.resolve(stream.dir) + path.sep)) return null;
        return resolved;
    }

    /** Records a playlist poll so the listener shows up in the count. */
    trackListener(roomId: string, clientKey: string): void {
        const stream = this.streams.get(roomId);
        if (!stream) return;
        stream.listeners.set(clientKey, Date.now());
    }

    getListenerCount(roomId: string): number {
        const stream = this.streams.get(roomId);
        if (!stream) return 0;

        const cutoff = Date.now() - LISTENER_WINDOW_MS;
        for (const [key, lastSeen] of stream.listeners) {
            if (lastSeen < cutoff) stream.listeners.delete(key);
        }
        return stream.listeners.size;
    }

    /** Tears down the ffmpeg process and removes the room's segments. */
    async stop(roomId: string): Promise<void> {
        const stream = this.streams.get(roomId);
        if (!stream) return;
        this.streams.delete(roomId);

        try {
            stream.process.stdin?.end();
        } catch {}
        // Give ffmpeg a moment to flush the last segment, then force-kill
        const killTimer = setTimeout(() => {
            try { stream.process.kill("SIGKILL"); } catch {}
        }, 3000);
        stream.process.once("exit", () => clearTimeout(killTimer));

        try {
            await fs.remove(stream.dir);
        } catch (e) {
            console.error(`❌ [HLS ${roomId}] Cleanup failed:`, e);
        }
        console.log(`📡 [HLS ${roomId}] Live pipeline stopped`);
    }

    /** Stops every active pipeline (server shutdown). */
    async stopAll(): Promise<void> {
        await Promise.all([...this.streams.keys()].map(id => this.stop(id)));
    }
}
